### PR TITLE
Removed require 'rbsecp256k1/rbsecp256k1' from lib/rbsecp256k1.rb

### PR DESCRIPTION
**Pull request by schinery**
Fix for https://github.com/etscrivner/rbsecp256k1/issues/61 which I've tested in my previously failing app using `gem "rbsecp256k1", git: "https://github.com/schinery/rbsecp256k1"`.

Also updated the test matrix to include Ruby 3.1 and 3.2.

### CODE REVIEW

**Review by q9f — APPROVED** [review]

**Comment by q9f** [comment]
👍🏼  makes sense. let's see what the CI says.

**Comment by etscrivner** [comment]
@schinery I've fixed the issue with failing workflow tests. If you can rebase against master and push up again we can see if tests pass.

**Comment by etscrivner** [comment]
@schinery IIRC `rbsecp256k1/rbsecp256k1` refers to the shared object found in the `rbsecp256k1` library folder, not a Ruby file, so it cannot be simply removed and I don't think the issue is simply an invalid import.

**Comment by schinery** [comment]
@etscrivner ah yeah, seems like that 😢

**Comment by schinery** [comment]
@etscrivner I'll close this and do a PR just for updating the test matrix

**Pull request closed without merging**
